services:
  avatar:
    container_name: avatar
    hostname: avatar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./assets:/avatar/assets
